### ISSUE TITLE
Multipolygon building not rendering correctly

### ISSUE THREAD

**Issue by bryceco** [Beakerboy/OSMBuilding#35]
I'm trying to view 
https://www.openstreetmap.org/relation/3067442
using
https://beakerboy.github.io/OSMBuilding/index.html?type=relation&id=3067442
but the building shape is totally wrong. 

Is this a bug, a defect in the OSM data, or something I'm doing wrong?

**Comment by Beakerboy** [comment]
It looks like it’s rendering part of the building next door instead. The fact that there is no grid beneath the building tells me some error occurred, but nothing is displaying to the error console. 

Thanks for reporting this! I’ll let you know what I find.

**Comment by Beakerboy** [comment]
The Westbank Frye looks pretty cool:
https://beakerboy.github.io/OSMBuilding/index.html?id=895975965

**Comment by Beakerboy** [comment]
It might be because there are buildings inside the building, which are not tagged as building parts.

**Comment by bryceco** [comment]
> The code will extract the gps data from a relation and then grab all the ways within the bounds of this object as a way to find any building parts.

I see. It's more complicated than I realized!

**Comment by Beakerboy** [comment]
So, yeah the issue is: a multipolygon is just a complicated “way”. If there are no parts or buildings inside of it, it will just render a generic outine. If there are buildings inside it it will render all the parts and only the parts.

the best way to do this is to use a building relation. The relation contains all parts and they are then all rendered individually.
https://wiki.openstreetmap.org/wiki/Relation:building

**Comment by Beakerboy** [comment]
I changed the inner buildings to also have a building:type = yes and it is not rendering the inner parts. If you want the ground floor to also be rendered, you should probably just change the main outline to be the building and all the multipolygon as a part with like three floors, and change the other buildings to have 10 floors or whatever.

**Comment by Beakerboy** [comment]
I’ve updated OSM a little with fake data. Check the render and tweak as needed

**Comment by bryceco** [comment]
I see. It's not my goal to fix this particular building, it's just something I noticed while looking into https://github.com/bryceco/GoMap/issues/728

**Comment by bryceco** [comment]
It looks much better now! 

I don't know anything about tagging conventions for building parts. Would you say that the building was tagged correctly but your code doesn't handle that situation, or that the tagging on the building was incorrect?

**Comment by Beakerboy** [comment]
My code follows convention as far as I know. Feel free to ask any questions and look at some of the example buildings that I link to  if you want to see how to tag different building and roof shapes, colors, and materials.

**Comment by Beakerboy** [comment]
**I didn’t know who you were** I love Go Map!! I’ve used it for years!

**Comment by bryceco** [comment]
That's great! 😃

**Comment by Beakerboy** [comment]
I see you’re also a nethack fan. I’ve been playing since the ‘90s and never ascended.

**Comment by bryceco** [comment]
Yeah I always stop paying attention or rush too much somewhere along the way and get killed.
